### ISSUE TITLE
"Using the compiler testing framework"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#10]
This section should describe how to compiler is tested. Substantial work has been done but there remains more to document:

- [x] discuss bors, travis, platform emulation (#66 )
- [ ] crater: what is it and why is it useful? How do you request a crater run and when should you to do so? (#151)
- [ ] maybe talk about "perf runs" too (#151)
- [x] rustdoc tests (cc @QuietMisdreavus)
- [x] talk about unit tests from libs and things (#62)
- [x] Doctests: How to run the doc tests in the standard library.  Other doc testing steps like linkchecker. (#62)
- [x] distcheck (#62)
- [x] mention that tests also get run for individual packages, such as bootstrap, cargo, rls, rustfmt, miri, clippy, cargotest. (#62)

**Comment by mark-i-m** [comment]
See #47 and #53

**Comment by mark-i-m** [comment]
@QuietMisdreavus #47 has landed :)
