### ISSUE TITLE
move over the rustc README 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#2]
There is a lot of existing content scattered in READMEs through rustc. We should move over that content. To start, [the rustc README](https://github.com/rust-lang/rust/blob/master/src/librustc/README.md) is a good candiate. It desribes the layout of the crates and contains a glossary (oh, we should probably add the glossary to its own chapter).

EDIT(@mark-i-m): Added TODOs

EDIT2(@mark-i-m): A lot of the content of the READMEs is redundant with content we already have, so please check that the content you are moving over is not already in the appropriate chapter. If it is, please post here, so we can check it off the list :smile: 

TODOs:
- [x] Overall arch: https://github.com/rust-lang/rust/blob/master/src/librustc/README.md
- [x] Dependency tracking/Incr. Compl.: https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/README.md
    - Actually, I think the chapter in this book is _more up-to-date_ than the README, which doesn't have red-green in it... There is some info in the READMEs, such as testing and debugging, that is not TMK in the book yet. - @mark-i-m
    - See rust-lang/rust#47935
    - See #87 
    - See #92 
- [x] HIR: https://github.com/rust-lang/rust/blob/master/src/librustc/hir/README.md
- [x] Type Inference: https://github.com/rust-lang/rust/blob/master/src/librustc/infer/README.md (#31)
- [x] MIR: https://github.com/rust-lang/rust/blob/master/src/librustc/mir/README.md (#36)
- [x] Trait resolution: https://github.com/rust-lang/rust/blob/master/src/librustc/traits/README.md
- [x] The `ty` module: https://github.com/rust-lang/rust/blob/master/src/librustc/ty/README.md
- [x] ./src/librustc/infer/region_constraints/README.md
    - I'm not sure we want to move this one over since it will soon be obsolete. #67 describes the new system (NLL). (Agreed -@nikomatsakis)
- [x] ./src/librustc/infer/lexical_region_resolve/README.md
   - Same here  (Agreed -@nikomatsakis)
- [x] ./src/librustc/infer/higher_ranked/README.md
    - [x] Skolemization (#67) -- This material is different from what is [covered in the rustc-guide](https://github.com/rust-lang-nursery/rustc-guide/pull/67), because the rustc-guide is describing the newer system we are aiming to add, and this is covering the older system we currently use.  (-@nikomatsakis)
    - [x] LUB/GLB -- same here (-@nikomatsakis)
- [x] ./src/librustc/ty/maps/README.md
- [x] ./src/librustc_data_structures/obligation_forest/README.md
    -  (I probably wouldn't move this over either. -@nikomatsakis)
- [x] ./src/librustc_typeck/variance/README.md (#85)
- [x] ./src/librustc_typeck/check/method/README.md (#85)
- [x] ./src/librustc_typeck/README.md (#85)
- [x] ./src/librustc_borrowck/borrowck/README.md
    - This too is basically obsolete. The NLL RFC offers better coverage of the new-and-shiny borrow checker, and we should add more of that material, I think. -@nikomatsakis
- [x] Rustdoc README from rust-lang/rust#48283 (#86 )

**Comment by mark-i-m** [comment]
@nikomatsakis What is the status of the README about dependency tracking... is there any content there that needs to be moved over to the book still?

**Comment by nikomatsakis** [comment]
@mark-i-m good question. I'm not entirely sure how much of that material is still relevant.

**Comment by mark-i-m** [comment]
cc @michaelwoerister ?

**Comment by mark-i-m** [comment]
I'm going to go ahead and close this. We can augment the dep. tracking chapters later if we want.

**Comment by mark-i-m** [comment]
It looks like there are a few more to do... updated the list above.

**Comment by mark-i-m** [comment]
@nikomatsakis Is  ./src/librustc_borrowck/borrowck/README.md still relevant?

**Comment by mark-i-m** [comment]
also, do we want to move over ./src/librustc/infer/region_constraints/README.md  and ./src/librustc/infer/lexical_region_resolve/README.md  which describe the old region inference system?

**Comment by mark-i-m** [comment]
After #92 this will be done :tada:

**Comment by mark-i-m** [comment]
:tada:
